Repository THD-AI-2023/Devablos-Project-V2, pull requests merged in 2024-07, with the labels that each got.

#35 Feature/user-handling-clien-side
  README.md
  client/.env.examle
  client/src/App.js
  server/Dockerfile
Labels: bug, feature

#39 Enhancement/button thingy pretty
  client/src/App.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
Labels: enhancement

#40 Feature: Enable WebSocket and HTTPS Protocols with Docker Integration
  client/.env.examle
  client/Dockerfile
  client/src/App.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  docker-compose.yml
  server/.env.example
  server/Dockerfile
  server/package.json
  server/src/controllers/assistantController.js
  server/src/server.js
  server/swagger.js
Labels: feature, refactor, security

#41 Feature: Enhanced Documentation and Environment Setup for Devablos Project V2
  README.md
  client/.env.example
  client/README.md
  client/public/banner-1200x600.png
  client/public/banner.png
  client/public/favicon_1.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  server/.env.example
  server/README.md
Labels: chore, feature, optimization
