Repository THD-AI-2023/Devablos-Project-V2, pull requests merged in 2024-06, with the labels that each got.

#7 Security: Implement SSL Encryption and HTTP to HTTPS Redirection
  server/.env.example
  server/.gitignore
  server/package.json
  server/src/app.js
  server/src/server.js
Labels: feature, security

#8 Sync: Merge Dev-Server into Main
  server/.env.example
  server/.gitignore
  server/package.json
  server/src/app.js
  server/src/server.js
Labels: chore, feature, security

#12 Feature: Implement WebSocket Server for Real-time Communication and Session Management
  main.py
  server/.env.example
  server/.gitignore
  server/package.json
  server/src/controllers/openaiController.js
  server/src/routes/openaiRoutes.js
  server/src/routes/openaiWsRoutes.js
  server/src/services/openaiService.js
  server/src/sockets/wsServer.js
  server/src/utils/connection.js
Labels: feature

#13 Feature: Implement WebSocket Client for Real-time Communication and Improved UX
  client/.env.example
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Chat.css
  client/src/components/Chat.js
  client/src/components/Message.css
  client/src/components/Message.js
  client/src/components/Navbar.css
  client/src/components/Navbar.js
  client/src/components/WebSocketStatus.css
  client/src/components/WebSocketStatus.js
Labels: feature

#20 Feature: Deployment Setup for Devablos V2 API
  .github/workflows/dependency-review.yml
  .github/workflows/dev-server_devablos-v2-api.yml
  server/src/server.js
Labels: feature

#21 chore: Update swagger.js with new base URL for Azure Deployment
  server/swagger.js
Labels: optimization

#22 feature/added weather function with API call to OpenWeather
  server/.env.example
  server/src/controllers/assistantController.js
  server/src/services/assistantService.js
Labels: feature

#23 feature/user-handling-server
  server/.env.example
  server/src/app.js
  server/src/controllers/assistantController.js
  server/src/routes/assistantRoutes.js
  server/src/services/assistantService.js
Labels: enhancement, feature

#25 Feature/websocket implementation assistant
  server/.env.example
  server/package.json
  server/src/controllers/assistantController.js
  server/src/routes/assistantWsRoutes.js
  server/src/services/assistantService.js
  server/src/sockets/wsServer_Assistant.js
  server/src/sockets/wsServer_ChatGPT.js
Labels: feature

#27 bugfix/dev-server
  server/.env.example
  server/package.json
  server/src/controllers/assistantController.js
  server/src/routes/assistantRoutes.js
  server/src/routes/assistantWsRoutes.js
  server/src/services/assistantService.js
  server/src/sockets/wsServer_Assistant.js
  server/src/sockets/wsServer_ChatGPT.js
Labels: bug, bugfix

#29 Feature: Add Dockerfile and GitHub Actions Workflow for Client Deployment
  .github/workflows/feature-deployment-client_devablos-v2.yml
  client/.env.example
  client/Dockerfile
  docker-compose.yml
Labels: feature, testing

#30 Add Docker Compose Configuration for Server and Update Server Dockerfile
  docker-compose.yml
  server/Dockerfile
  server/package.json
Labels: feature

#31 Feature: WebSocket Implementation and Docker Compose Configuration
  docker-compose.yml
  server/.env.example
  server/Dockerfile
  server/package.json
  server/src/controllers/assistantController.js
  server/src/routes/assistantRoutes.js
  server/src/routes/assistantWsRoutes.js
  server/src/services/assistantService.js
  server/src/sockets/wsServer_Assistant.js
  server/src/sockets/wsServer_ChatGPT.js
Labels: feature

#33 Feature: Client Deployment and Configuration Enhancements
  .github/workflows/feature-deployment-client_devablos-v2.yml
  client/.env.example
  client/Dockerfile
  client/public/favicon.ico
  client/public/favicon_1.ico
  client/public/index.html
  client/src/components/Navbar.css
  docker-compose.yml
Labels: feature

#37 Update SSL configuration for serving the client build
  client/Dockerfile
  client/package.json
  client/src/logo.svg
  server/Dockerfile
Labels: feature, bugfix
